import type { Metadata } from "next";
import "./globals.css";

import Header from "./components/header";
import Main from "./components/main";
import Footer from "./components/footer";


export const metadata: Metadata = {
  title: "My-app-next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Header></Header>
        <Main>{children}</Main>
        <Footer></Footer>
      </body>
    </html>
  );
}
